import Head from "next/head";

export function SearchPage() {
	return (
		<div>
			<Head>
				<title>MELI</title>
				<meta content="Generated by create next app" name="description" />
				<link href="/favicon.ico" rel="icon" />
			</Head>
		</div>
	);
}

export default SearchPage;
